/**
 * dsh-why web — page chrome strings. Finding-level copy (titles, symptoms,
 * history, fix steps) comes from the shared lib/i18n.mjs so the web and the CLI
 * speak with one voice; these are only the strings the page itself owns.
 *
 * @module dsh-why/web/strings
 */

const STR = {
  en: {
    slogan: 'Every crash deserves an honest explanation.',
    navGithub: 'GitHub',
    trust: 'Zero dependencies · Read-only · Nothing you paste leaves this browser',
    cmdLabel: 'Or run it locally — it reads your actual install:',
    pasteLabel: 'Paste the error',
    pastePlaceholder: 'The red screen or the console line, e.g.\nfailed to import loader entry f059e6c1 (dsh-at-file): client-modules: require("@deepseek-ai/dsh-client-runtime/client") missed the module table',
    versionLabel: 'Your dsh version',
    versionUnknown: 'Unknown',
    versionNote: 'The module table is baked into each shell build — pick the version you actually run.',
    diagnose: 'Diagnose',
    paste: 'Paste',
    copy: 'Copy report',
    copying: 'Copied ✓',
    copylink: 'Copy link',
    copylinkDone: 'Link copied ✓',
    privacy: 'Diagnosed entirely in your browser. Data (module tables, known fixes, compat matrix) is fetched from dsh-insights.com.',
    provenance: 'Web diagnosis — no local install was read. Graph rows come from the published per-shell roster (a superset of the real boot graph); your own plugins and profile are invisible here.',
    empty: 'Paste the loader error above. You can also drop a whole console dump — only the recognized lines are used.',
    bare: 'That red screen names no specific module or plugin, and this page cannot scan your machine. Run the CLI for a full local diagnosis:',
    bareCmd: 'npx dsh-why',
    unrecognizedTitle: 'Not recognized (yet)',
    unrecognized: 'This error shape is not in the pattern list — send it in so the library grows. The CLI may still help:',
    rowsFailed: 'the published row roster was unreachable, so unresolvable requires are reported as unclassified warnings, never as crashes.',
    rowsRosterNote: 'shell graph rows: published roster (a superset of the real boot graph — your local install is not read)',
    internalError: 'dsh-why: internal error — please report it',
    notError: 'This looks like a dsh-why report, not a loader error. Paste the red screen (or the console line starting with client-modules:) — that is what this page diagnoses.',
    loading: 'Diagnosing…',
    reportTitle: 'Diagnosis',
    allGreen: 'All clear',
    allGreenDetail: 'Everything in the pasted error resolves on the selected shell.',
    summaryErrors: 'crash',
    summaryWarnings: 'warning',
    summaryNotes: 'note',
    summaryConditional: 'conditional',
    summaryUnclassified: 'unclassified',
    findingsTitle: 'Findings',
    copyIssue: 'Copy issue',
    issueCopied: 'Issue copied ✓',
    timelineNever: 'never shipped in any shell module table',
    timelinePresent: 'present since',
    timelineRemoved: 'removed in',
    timelineNow: 'now',
    ecosystem: 'plugins ecosystem-wide hit the same module',
    ecosystemOne: 'plugin ecosystem-wide hits the same module',
    knownFixTitle: 'Known fix',
    collapsed: 'expand',
    expanded: 'collapse',
    envShell: 'shell (module table)',
    envSeed: 'module table snapshot',
    envUpstream: 'live',
    envBundled: 'bundled',
    footerNote: 'dsh-why — the “why did my dsh break” diagnostic. Same rule base as the CLI, one verdict either way.',
  },
  zh: {
    slogan: '每一次崩溃，都值得一个诚实的解释。',
    navGithub: 'GitHub',
    trust: '零依赖 · 只读 · 你粘贴的内容绝不离开浏览器',
    cmdLabel: '或在本机运行——它能读到你的真实安装：',
    pasteLabel: '粘贴报错',
    pastePlaceholder: '红屏文字或那行控制台输出，例如\nfailed to import loader entry f059e6c1 (dsh-at-file): client-modules: require("@deepseek-ai/dsh-client-runtime/client") missed the module table',
    versionLabel: '你的 dsh 版本',
    versionUnknown: '不知道',
    versionNote: '模块表是烘焙进每个 shell 构建的——选你实际运行的版本，判定才准。',
    diagnose: '诊断',
    paste: '粘贴',
    copy: '复制报告',
    copying: '已复制 ✓',
    copylink: '复制链接',
    copylinkDone: '链接已复制 ✓',
    privacy: '全程在你的浏览器里诊断。数据（模块表、已知修法、兼容矩阵）取自 dsh-insights.com。',
    provenance: '网页诊断——未读取本机安装。图行清单来自观测站按 shell 版本发布的名册（是真实 boot graph 的超集）；你自己装的插件和 profile 在这里看不到。',
    empty: '把上面的加载器报错粘进来。整段控制台输出也可以直接丢——只取认得出来的那几行。',
    bare: '那段红屏没有指明具体的模块或插件，而这个网页无法扫描你的机器。要完整本机诊断请运行 CLI：',
    bareCmd: 'npx dsh-why',
    unrecognizedTitle: '暂不认识',
    unrecognized: '这个报错形态不在已支持列表里——发给我们扩充规则库。CLI 也许仍能帮上忙：',
    rowsFailed: '观测站的图行名册连不上，因此无法解析的 require 一律报「无法判定」警告，绝不误报崩溃。',
    rowsRosterNote: 'shell 图行：观测站发布的名册（真实 boot graph 的超集——未读取本机安装）',
    internalError: 'dsh-why：内部错误——请反馈',
    notError: '这看起来是一份 dsh-why 报告，不是加载器报错。请粘贴红屏（或以 client-modules: 开头的控制台行）——那才是本页诊断的对象。',
    loading: '诊断中…',
    reportTitle: '诊断结果',
    allGreen: '全绿',
    allGreenDetail: '粘贴的报错里，所有引用都能在你选的 shell 上解析。',
    summaryErrors: '崩溃',
    summaryWarnings: '警告',
    summaryNotes: '备注',
    summaryConditional: '条件可解析',
    summaryUnclassified: '无法判定',
    findingsTitle: '问题列表',
    copyIssue: '复制 issue',
    issueCopied: 'issue 已复制 ✓',
    timelineNever: '从未进入任何 shell 模块表',
    timelinePresent: '自',
    timelineRemoved: '移除于',
    timelineNow: '现在',
    ecosystem: '个插件全生态同病',
    ecosystemOne: '个插件全生态同病',
    knownFixTitle: '已知修法',
    collapsed: '展开',
    expanded: '收起',
    envShell: 'shell（模块表）',
    envSeed: '模块表快照',
    envUpstream: '线上',
    envBundled: '包内',
    footerNote: 'dsh-why——「我的 dsh 为什么挂了」诊断。与 CLI 同一套规则库，网页和终端一个口径。',
  },
}

export function webT(lang) {
  return STR[lang] ?? STR.en
}
